Make the confirm close dialog optional.
slaclab/pydm pull request #736
Opened 2021-05-21 16:37 UTC by mattgibbs

This PR adds a new config option that specifies whether PyDM displays the quit confirmation dialog box or not when closing a window.  This option is driven by an environment variable, `PYDM_CONFIRM_QUIT`.  If this variable is set to "Y", "T", "1", or "TRUE" (case insensitive), PyDM will show the quit dialog.  If the environment variable is set to any other value, or if it is not set at all, PyDM will not show the dialog.

@ivany4 This is relevant to you - to keep the current behavior, you'll have to set this environment variable.

2021-05-24 19:40 UTC, hhslepicka commented on pydm/main_window.py
> +            return callback()
You need to execute the callback, not return it.
```suggestion
            callback()
```

2021-05-24 19:41 UTC, hhslepicka requested changes
Change won't work. You need to execute the callback not return it. 😉

2021-05-24 19:47 UTC, hhslepicka approved these changes

2021-05-24 19:49 UTC, mattgibbs commented
Thanks @hhslepicka!  It technically did work, because it was returning the _result_ of `callback()`, but you are right - not the right way to do it.  Fixed.

2021-05-24 19:50 UTC, merged

2021-06-09 12:52 UTC, ivany4 commented
Thanks @mattgibbs. I was actually not the fan of that modal dialog, merely triad to improve the consistency of quitting behaviors :)